#!/usr/bin/env node
// Copies the DARs the owner uploads through the DevNet Console into .local/devnet/dars/ and writes the upload
// manifest (docs/devnet/upload-manifest.json and .md): file, size, SHA-256, main package id, name, version and the
// packages each DAR embeds, in upload order. Build first (CLAUDE.md): dpm build --all in daml/collara.
//
//   node scripts/devnet/build-dars.mjs [--check]
//
// --check only compares the built DARs with the committed manifest (exit 1 on a difference).
import { copyFileSync, mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { basename, join, relative } from "node:path";
import { inspectDar } from "../localnet/lib.mjs";
import { DARS_DIR, embeddedPackages, isMain, MANIFEST_JSON, readManifest, REPO_ROOT } from "./lib.mjs";

/**
 * Upload order. governance-core-v1 first: it carries GovernanceRules (and the governance-action-v1 interface and
 * splice-util it depends on), which the contracts DAR does not embed. collara-contracts embeds collara-governance and
 * governance-action-v1, so those two need no upload of their own.
 */
export const UPLOADS = [
  {
    source: "daml/collara/vendor-dars/governance-core-v1-0.1.0.dar",
    why: "DM GovernanceRules (Tier A governance of the verifier registry); not embedded in the contracts DAR",
  },
  {
    source: "daml/collara/contracts/.daml/dist/collara-contracts-0.2.0.dar",
    why: "Collara contracts; embeds collara-governance 0.1.0 and governance-action-v1 0.1.0",
  },
];

export function buildManifest() {
  return UPLOADS.map((upload, index) => {
    const path = join(REPO_ROOT, upload.source);
    const dar = inspectDar(path);
    return {
      order: index + 1,
      file: basename(path),
      source: upload.source,
      sizeBytes: statSync(path).size,
      sha256: dar.sha256,
      mainPackageId: dar.mainPackageId,
      name: dar.name,
      version: dar.version,
      sdkVersion: dar.sdkVersion ?? null,
      embeds: embeddedPackages(readFileSync(path)),
      why: upload.why,
    };
  });
}

function markdown(entries) {
  const lines = [
    "# DevNet upload manifest",
    "",
    "Generated by `node scripts/devnet/build-dars.mjs` from the DARs built at this commit (`dpm build --all` in `daml/collara`). The files are copied to `.local/devnet/dars/`. Upload them through the DevNet Console (Collections → Upload DAR) **in this order**; the JSON Ledger API of the shared node does not accept `/v2/dars` uploads. Same name and version with different content is rejected by the participant, so never edit a DAR after uploading it: bump the package version instead.",
    "",
    "| # | File | Size (bytes) | SHA-256 | Main package | Name | Version |",
    "|---|---|---|---|---|---|---|",
    ...entries.map((e) => `| ${e.order} | \`${e.file}\` | ${e.sizeBytes} | \`${e.sha256}\` | \`${e.mainPackageId}\` | \`${e.name}\` | ${e.version} |`),
    "",
    "## What each DAR embeds (besides daml-prim and daml-stdlib)",
    "",
    ...entries.flatMap((e) => [
      `**${e.order}. \`${e.file}\`**: ${e.why}.`,
      "",
      ...e.embeds.map((p) => `- \`${p.name}\` ${p.version}: \`${p.packageId}\``),
      "",
    ]),
    "## Not uploaded",
    "",
    "- `collara-governance-0.1.0.dar` and `governance-action-v1-0.1.0.dar`: already inside `collara-contracts-0.2.0.dar` (same package ids).",
    "- `collara-scripts` and `collara-tests`: depend on daml-script; the tests package defines a test-only attacker template. Never upload them.",
    "",
    "## Checks after upload",
    "",
    "`node scripts/devnet/preflight.mjs` (with credentials) lists every main package id above as present and vetted, or names the missing one. `governance-core-v1` embeds `splice-util` 0.1.4; if the participant already has a different package under that name and version, the upload is rejected: report the exact Console error (docs/devnet/owner-checklist.md, step h).",
    "",
  ];
  return lines.join("\n");
}

if (isMain(import.meta.url)) {
  const entries = buildManifest();
  if (process.argv.includes("--check")) {
    const committed = readManifest();
    const same = JSON.stringify(committed?.dars ?? null) === JSON.stringify(entries);
    console.log(same ? "upload manifest matches the built DARs" : "upload manifest differs from the built DARs: run node scripts/devnet/build-dars.mjs");
    process.exitCode = same ? 0 : 1;
  } else {
    mkdirSync(DARS_DIR, { recursive: true });
    for (const e of entries) {
      copyFileSync(join(REPO_ROOT, e.source), join(DARS_DIR, `${String(e.order).padStart(2, "0")}-${e.file}`));
      console.log(`${e.order}. ${e.file}  ${e.sizeBytes} bytes  sha256 ${e.sha256}  main ${e.mainPackageId} (${e.name} ${e.version})`);
    }
    writeFileSync(MANIFEST_JSON, `${JSON.stringify({ generatedBy: "scripts/devnet/build-dars.mjs", dars: entries }, null, 2)}\n`);
    writeFileSync(MANIFEST_JSON.replace(/\.json$/, ".md"), markdown(entries));
    console.log(`copied to ${relative(REPO_ROOT, DARS_DIR)}; wrote ${relative(REPO_ROOT, MANIFEST_JSON)} and upload-manifest.md`);
  }
}
