"use client";

import { errorMessage } from "@collara/api-client";
import { CONFIRMATION_COPY, STATUS_COPY, type Report } from "@collara/domain";
import { DownloadIcon } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { ErrorState } from "@/components/collara/error-state";
import { LoadingState } from "@/components/collara/loading-state";
import { StatusBadge } from "@/components/collara/status-badge";
import { Button } from "@/components/ui/button";
import { useCollara } from "@/lib/collara-client";
import { formatUtcDateTime, shortId } from "@/lib/format";
import { useReportList } from "@/lib/queries";
import { openDownload } from "./download";
import { EmptyRow, TableRegion, TD, TR } from "./table-region";

function checksumText(checksum: string | null): string {
  if (!checksum) return "—";
  const [algorithm, value] = checksum.includes(" ") ? checksum.split(" ", 2) : ["sha256", checksum];
  return `${algorithm} ${shortId(value ?? "", 6, 6)}`;
}

/** Export history (S §9.18): requester-scoped jobs with cut-off, schema version and checksum. */
export function AuditExports() {
  const { client } = useCollara();
  const reports = useReportList();
  const [downloading, setDownloading] = useState<string | null>(null);

  async function download(report: Report) {
    setDownloading(report.ref);
    try {
      // Access is re-checked at download: a revoked or expired grant blocks it.
      const link = await client.reports.download(report.ref);
      openDownload(link.url, `${report.ref}-${report.caseId}.${report.format.toLowerCase()}`);
    } catch (error) {
      toast.error(errorMessage(error));
    } finally {
      setDownloading(null);
    }
  }

  return (
    <div className="flex flex-col gap-3">
      {reports.isError ? (
        <ErrorState error={reports.error} onRetry={() => void reports.refetch()} />
      ) : reports.isPending ? (
        <LoadingState variant="table" rows={3} label="Loading exports…" />
      ) : (
        <TableRegion
          label="Export jobs"
          head={["Report", "Scope", "Requested by", "Generated (UTC)", "Cut-off · coverage watermark", "Checksum", "State", ""]}
          minWidth="min-w-[1100px]"
        >
          {reports.data.items.map((r) => (
            <tr key={r.ref} className={TR}>
              <td className={TD}>
                <span className="font-mono text-[12.5px]">{`${r.ref} · ${r.caseId}`}</span>
                <span className="block text-[12px] text-fg-subtle">{`${r.format} · schema ${r.schemaVersion}`}</span>
              </td>
              <td className={`${TD} text-[12.5px]`}>{r.scope}</td>
              <td className={TD}>{r.requestedBy}</td>
              <td className={`${TD} font-mono text-[12px] whitespace-nowrap text-fg-muted`}>{r.generatedAt ? formatUtcDateTime(r.generatedAt) : "—"}</td>
              <td className={`${TD} font-mono text-[12px] text-fg-muted`}>
                {`${r.cutoff.offset !== null ? `offset ${r.cutoff.offset}` : "no ledger offset"} · cut-off ${formatUtcDateTime(r.cutoff.at)}`}
              </td>
              <td className={`${TD} font-mono text-[12px] whitespace-nowrap text-fg-muted`} title={r.checksum ?? undefined}>
                {checksumText(r.checksum)}
              </td>
              <td className={`${TD} whitespace-nowrap`}>
                <StatusBadge status={r.state} />
              </td>
              <td className={`${TD} text-right`}>
                {r.state.value === "READY" ? (
                  <Button
                    size="sm"
                    variant="outline"
                    disabled={downloading === r.ref}
                    onClick={() => void download(r)}
                    aria-label={`Download ${r.ref} (${r.format})`}
                  >
                    <DownloadIcon aria-hidden="true" />
                    Download
                  </Button>
                ) : null}
              </td>
            </tr>
          ))}
          {reports.data.items.length === 0 ? <EmptyRow colSpan={8}>No exports have been generated by your organization yet.</EmptyRow> : null}
        </TableRegion>
      )}
      <p className="font-mono text-[12px] text-fg-subtle">{CONFIRMATION_COPY.REPORT_LABEL}</p>
      <p className="text-[12px] leading-relaxed text-fg-subtle">
        {STATUS_COPY.SCOPED_EXPORT} Access is re-evaluated at generation and at download. Each report carries a cut-off, a schema version and a
        checksum; it is not a complete global history.
      </p>
    </div>
  );
}
