// The key that encrypts DEVNET's stored refresh token (ledger_credentials, AES-256-GCM in @collara/db). It lives
// OUTSIDE the database: in .env.devnet or the host's secret manager, generated by `node scripts/devnet/gen-key.mjs`.
//   DEVNET_CREDENTIAL_KEY           base64 of exactly 32 random bytes (the current key; every write uses it)
//   DEVNET_CREDENTIAL_KEY_ID        short id stored next to each ciphertext (and bound into its AAD)
//   DEVNET_CREDENTIAL_KEY_PREVIOUS  optional, comma-separated `<id>:<base64>`: older keys, used only to decrypt rows
//                                   written before a rotation; the next refresh re-encrypts with the current key
// Messages here name variables and key ids, never key material.

export const CREDENTIAL_KEY_ENV = "DEVNET_CREDENTIAL_KEY";
export const CREDENTIAL_KEY_ID_ENV = "DEVNET_CREDENTIAL_KEY_ID";
export const CREDENTIAL_KEY_PREVIOUS_ENV = "DEVNET_CREDENTIAL_KEY_PREVIOUS";
export const GEN_KEY_COMMAND = "node scripts/devnet/gen-key.mjs";

/** Key ids: letters, digits, dot, dash, underscore (no ':' or ',', which separate DEVNET_CREDENTIAL_KEY_PREVIOUS). */
const KEY_ID = /^[A-Za-z0-9._-]{1,64}$/;
/** Canonical standard base64 of 32 bytes: 43 characters and one '='. */
const KEY_BASE64 = /^[A-Za-z0-9+/]{43}=$/;

export interface CredentialKeyMaterial {
  readonly id: string;
  /** 32 bytes. */
  readonly key: Uint8Array;
}

export interface CredentialKeyring {
  readonly current: CredentialKeyMaterial;
  readonly previous: readonly CredentialKeyMaterial[];
}

export interface CredentialKeyEnv {
  readonly DEVNET_CREDENTIAL_KEY?: string | undefined;
  readonly DEVNET_CREDENTIAL_KEY_ID?: string | undefined;
  readonly DEVNET_CREDENTIAL_KEY_PREVIOUS?: string | undefined;
}

export interface CredentialKeyIssue {
  readonly path: string;
  readonly message: string;
}

function decodeKey(value: string): Uint8Array | null {
  if (!KEY_BASE64.test(value)) return null;
  const bytes = Buffer.from(value, "base64");
  return bytes.length === 32 ? new Uint8Array(bytes) : null;
}

function parse(env: CredentialKeyEnv): { keyring: CredentialKeyring | null; issues: CredentialKeyIssue[] } {
  const issues: CredentialKeyIssue[] = [];
  const raw = env.DEVNET_CREDENTIAL_KEY?.trim();
  const id = env.DEVNET_CREDENTIAL_KEY_ID?.trim();
  let key: Uint8Array | null = null;
  if (!raw) {
    issues.push({ path: CREDENTIAL_KEY_ENV, message: `DEVNET needs ${CREDENTIAL_KEY_ENV} (the refresh token is stored encrypted): run ${GEN_KEY_COMMAND} and put its output into .env.devnet or the host's secret manager` });
  } else {
    key = decodeKey(raw);
    if (!key) issues.push({ path: CREDENTIAL_KEY_ENV, message: `${CREDENTIAL_KEY_ENV} must be standard base64 of exactly 32 bytes (44 characters ending in '='); generate one with ${GEN_KEY_COMMAND}` });
  }
  if (!id) {
    issues.push({ path: CREDENTIAL_KEY_ID_ENV, message: `DEVNET needs ${CREDENTIAL_KEY_ID_ENV} (printed by ${GEN_KEY_COMMAND})` });
  } else if (!KEY_ID.test(id)) {
    issues.push({ path: CREDENTIAL_KEY_ID_ENV, message: `${CREDENTIAL_KEY_ID_ENV} must be 1-64 characters of A-Z a-z 0-9 . _ -` });
  }
  const previous: CredentialKeyMaterial[] = [];
  const entries = (env.DEVNET_CREDENTIAL_KEY_PREVIOUS ?? "").split(",").map((e) => e.trim()).filter(Boolean);
  entries.forEach((entry, index) => {
    const at = entry.indexOf(":");
    const previousId = at > 0 ? entry.slice(0, at) : "";
    const previousKey = at > 0 ? decodeKey(entry.slice(at + 1)) : null;
    if (!KEY_ID.test(previousId) || !previousKey) {
      issues.push({ path: CREDENTIAL_KEY_PREVIOUS_ENV, message: `${CREDENTIAL_KEY_PREVIOUS_ENV} entry ${index + 1} must be <key id>:<base64 of 32 bytes>` });
      return;
    }
    if (previousId === id || previous.some((p) => p.id === previousId)) {
      issues.push({ path: CREDENTIAL_KEY_PREVIOUS_ENV, message: `key id ${previousId} appears more than once in ${CREDENTIAL_KEY_ID_ENV} / ${CREDENTIAL_KEY_PREVIOUS_ENV}` });
      return;
    }
    if (key && Buffer.from(previousKey).equals(Buffer.from(key))) {
      issues.push({ path: CREDENTIAL_KEY_PREVIOUS_ENV, message: `${CREDENTIAL_KEY_PREVIOUS_ENV} entry ${previousId} is the same key as ${CREDENTIAL_KEY_ENV}` });
      return;
    }
    previous.push({ id: previousId, key: previousKey });
  });
  if (issues.length || !key || !id) return { keyring: null, issues };
  return { keyring: { current: { id, key }, previous }, issues };
}

/** Reasons the credential key settings are unusable (empty = fine). Never contains key material. */
export function credentialKeyIssues(env: CredentialKeyEnv): CredentialKeyIssue[] {
  return parse(env).issues;
}

export class CredentialKeyConfigError extends Error {
  override readonly name = "CredentialKeyConfigError";
  readonly issues: readonly CredentialKeyIssue[];
  constructor(issues: readonly CredentialKeyIssue[]) {
    super(issues.map((i) => `${i.path}: ${i.message}`).join("\n"));
    this.issues = issues;
  }
}

/** The keyring from the environment; throws CredentialKeyConfigError (without key material) when unusable. */
export function parseCredentialKeyring(env: CredentialKeyEnv): CredentialKeyring {
  const { keyring, issues } = parse(env);
  if (!keyring) throw new CredentialKeyConfigError(issues);
  return keyring;
}

/**
 * Environment variables that must never carry the credential key into a browser bundle: any NEXT_PUBLIC_* whose
 * name mentions CREDENTIAL_KEY, or whose value contains the configured key.
 */
export function publicEnvKeyLeaks(env: Readonly<Record<string, string | undefined>>): string[] {
  const key = env.DEVNET_CREDENTIAL_KEY?.trim();
  const previous = (env.DEVNET_CREDENTIAL_KEY_PREVIOUS ?? "").split(",").map((e) => e.slice(e.indexOf(":") + 1).trim()).filter((v) => v.length >= 40);
  const secrets = [key, ...previous].filter((v): v is string => !!v && v.length >= 40);
  return Object.entries(env)
    .filter(([name, value]) => name.startsWith("NEXT_PUBLIC_") && (/CREDENTIAL_KEY/i.test(name) || (value !== undefined && secrets.some((s) => value.includes(s)))))
    .map(([name]) => name);
}
