// Reports: GET|POST /reports, GET /reports/:id/download (API_ENDPOINTS "reports.*"). Generation runs in the worker
// (apps/worker/src/jobs/handlers/export.ts); access is re-checked at download (short-lived link).
// Registered once under the /api prefix by ./index.ts: declare full paths here ("/cases/:id", not "/:id").
// Write path: APPLICATION command + export job; read path: export_jobs of the caller's organisation.
import { commandResultSchema, CreateReportRequestSchema, pageSchema, PageQuerySchema, ReportDownloadSchema, ReportSchema } from "@collara/domain";
import type { FastifyPluginAsyncZod } from "fastify-type-provider-zod";
import { IdempotencyHeadersSchema } from "../../workflow";
import { createReport, downloadReport, listReports } from "../../workflow/exports/reports";
import { financeDeps, RefParams } from "../../workflow/financing/http";
import type { WorkflowRouteOptions } from "./types";

export const reportRoutes: FastifyPluginAsyncZod<WorkflowRouteOptions> = async (app, opts) => {
  const deps = financeDeps(opts);

  app.get(
    "/reports",
    { schema: { tags: ["reports"], summary: "Case reports requested by the caller's organization", querystring: PageQuerySchema, response: { 200: pageSchema(ReportSchema) } } },
    async (request) => {
      const member = await request.requireActor();
      return listReports(deps, member, request.query);
    },
  );

  app.post(
    "/reports",
    {
      schema: {
        tags: ["reports"],
        summary: "Request a scoped case report (generated by the worker; application record, no ledger transaction)",
        headers: IdempotencyHeadersSchema,
        body: CreateReportRequestSchema,
        response: { 200: commandResultSchema(ReportSchema), 201: commandResultSchema(ReportSchema) },
      },
    },
    async (request, reply) => {
      const member = await request.requireActor();
      const created = await createReport(deps, member, request.body, request.headers["idempotency-key"], { id: request.id, log: request.log });
      return reply.code(created.created ? 201 : 200).send({ command: created.command, result: created.result });
    },
  );

  app.get(
    "/reports/:id/download",
    { schema: { tags: ["reports"], summary: "Short-lived (60 s) download link, issued after re-checking access", params: RefParams, response: { 200: ReportDownloadSchema } } },
    async (request) => {
      const member = await request.requireActor();
      return downloadReport(deps, opts.services.storage, member, request.params.id, { id: request.id, log: request.log });
    },
  );
};
